### ISSUE TITLE
Network performance degradation on 2.6.18 based kernels

### ISSUE THREAD

**Issue by chkp-zegman** [LIS/lis-next#118]
Network performance of LIS 4.0.11 (20150727) compared to LIS 3.5 shows a significant degradation.
Seems to be related to TX path.
Upload speeds of < 30KB/sec

**Comment by nickme** [comment]
Will try to reproduce the degradation.

**Comment by nickme** [comment]
Hi there,

Since minimal details were provided, we picked a version/environment to try to reproduce the issue.  I used an existing CentOS 5.8 x64 VM (2.6.18-308 kernel) Windows Server 2012 R2 host.  The iperf benchmark was used to collect the metrics.  We were not able to reproduce the reduction in throughput.  I tested where the iperf server was on a separate host, and where the iperf server was on the same host as the client VM.

Could you provide some details on your environment and configuration?

VM Client:
    CentOS 5.8 x64
    2GB RAM
    Gen 1 VM

client iperf command
    iperf3 -c 192.168.1.101 -t 60 -i 15

Test results:

iperf client and server on separate physical hosts.
             Interval    Transfer & Bandwidth (1 vCPU)    Transfer and Bandwidth (4 vCPU)
LIS 3.5      0-60        23.3 GBytes, 3.33 Gbits/sec      24.0 GBytes, 3.44 Gbits/sec
LIS 3.5.3    0-60        23.0 GBytes, 3.29 Gbits/sec      23.0 GBytes, 3.30 Gbits/sec
LIS 4.0.7    0-60        38.0 GBytes, 5.58 Gbits/sec      40.6 GBytes, 5.81 Gbits/sec
LIS 4.0.11   0-60        39.8 GBytes, 5.71 Gbits/sec      40.9 GBytes, 5.86 Gbits/sec

iperf client and server on same physical host
             Interval    Transfer & Bandwidth (1 vCPU)    Transfer and Bandwidth (4 vCPU)
LIS 3.5      0-60        16.2 GBytes, 2.32 Gbits/sec      13.7 GBytes, 1.96 Gbits/sec
LIS 3.5.3    0-60        16.0 GBytes, 2.29 Gbits/sec      14.3 GBytes, 2.04 Gbits/sec
LIS 4.0.7    0-60        31.6 GBytes, 4.53 Gbits/sec      33.9 GBytes, 4.86 Gbits/sec
LIS 4.0.11   0-60        32.1 GBytes, 4.60 Gbits/sec      37.0 GBytes, 5.30 Gbits/sec

thanks,

-Nick

**Comment by nickme** [comment]
Using the formatting options to make the data more readable (in the GitHub web view).

**iperf client and server on separate physical hosts.**
```
LIS version   Interval  Transfer & Bandwidth (1 vCPU)   Transfer and Bandwidth (4 vCPU)
 LIS 3.5      0-60      23.3 GBytes, 3.33 Gbits/sec     24.0 GBytes, 3.44 Gbits/sec
 LIS 3.5.3    0-60      23.0 GBytes, 3.29 Gbits/sec     23.0 GBytes, 3.30 Gbits/sec
 LIS 4.0.7    0-60      38.0 GBytes, 5.58 Gbits/sec     40.6 GBytes, 5.81 Gbits/sec
 LIS 4.0.11   0-60      39.8 GBytes, 5.71 Gbits/sec     40.9 GBytes, 5.86 Gbits/sec
```

**iperf client and server on same physical host**
```
LIS version   Interval  Transfer & Bandwidth (1 vCPU)   Transfer and Bandwidth (4 vCPU)
 LIS 3.5      0-60      16.2 GBytes, 2.32 Gbits/sec     13.7 GBytes, 1.96 Gbits/sec
 LIS 3.5.3    0-60      16.0 GBytes, 2.29 Gbits/sec     14.3 GBytes, 2.04 Gbits/sec
 LIS 4.0.7    0-60      31.6 GBytes, 4.53 Gbits/sec     33.9 GBytes, 4.86 Gbits/sec
 LIS 4.0.11   0-60      32.1 GBytes, 4.60 Gbits/sec     37.0 GBytes, 5.30 Gbits/sec
```

**Comment by chkp-zegman** [comment]
This was seen in Azure using several VM sizes (including - Standard_D2v2).
The degradation was seen with a TCP upload (not clear if you were using UDP or TCP in your tests).
The kernel was based on 2.6.18-92 (with additional patches).

**Comment by nickme** [comment]
Hi Tamir,

The test were performed using TCP.  iperf defaults to TCP unless the -u option is specified.

The 2.6.18-92 kernel ships in RHEL 5.2.  Neither LIS 3.5 or LIS 4.0.11 supports RHEL 5.2.  RHEL 5.2 support was added in LIS 4.1.0.  The oldest RHEL version supported by LIS 3.5 and LIS 4.0.11 is RHEL 5.5.  I repeated the tests using the versions of LIS you referenced on a RHEL 5.5 VM, and also a RHEL 5.2 VM with LIS 4.1.0.  The test environment has a dedicated link between the two hosts - there is no other traffic on the link other than what iperf generates.

**RHEL 5.5 x64 (2.6.18-194 kernel), iperf client and server on separate hosts**
```
LIS Version    Interval   Transfer & Bandwidth (1vCPU)    Transfer & Bandwidth (4vCPUs)
  LIS 3.5      0 - 60     22.6 GBytes, 3.24 Gbits/sec     22.9 GBytes, 3.28 Gbits/sec
  LIS 4.0.11   0 - 60     38.9 GBytes, 5.57 Gbits/sec     42.0 GBytes, 6.02 Gbits/sec
```

**RHEL 5.2 x64 (2.6.18-92 kernel), iperf client and server on separate hosts**
```
LIS Version    Interval   Transfer & Bandwidth (1vCPU)    Transfer & Bandwidth (4vCPUs)
  LIS 4.1.0    0 - 60     38.7 GBytes, 5.54 Gbits/sec     41.4 GBytes, 5.93 Gbits/sec
```

I was not able to reproduce a network performance degradation using RHEL 5.2 with the 2.6.18-92 kernel and a supported version of LIS.  I need to double check, but I believe we only support the more recent 6.x and 7.x images in Azure - but again, I need to double check.

thanks,

-Nick

**Comment by chkp-zegman** [comment]
After further research it seems the problem was that LIS 4.0 introduced support for NETIF_F_TSO but did not provide the ethtool ops to disable it.
In my test, an intermediate module assumed TSO was off, and this resulted in segments on the network with incorrect check sum.
To summarize, it would be good if LIS supports:
ethtool -K tso off

**Comment by nickme** [comment]
Hi Tamir,

Due to some work related travel and vacation, I'm just getting back to this.  ethtool support is in the 7.x tree.  It is no in the 6.x or 5.x tree.  I do not recall if there was a reason why ethtool support was not ported to 6.x and 5.x.  I will create two new issues for porting ethtool support - one for the 6.x and one for the 5.x trees.  

thanks,

-Nick

**Comment by chkp-zegman** [comment]
Thanks.
Closing this issue.
