### ISSUE TITLE
Unable to reduce the mtu to any value less than 1500 in a SLES 11 SP4

### ISSUE THREAD

**Issue by v-eslop** [LIS/lis-next#582]
Hello LIS team,

I am facing issues to reduce the mtu to any value less than 1500 in a SLES 11 SP4 Azure virtual machine created using a priority image available in the Azure marketplace.
The VM is running the latest kernel available in the official repositories "3.0.101-108.68-default".
And the issue is reproducible with the SLES 11 SP4 azure marketplace image using the default network configuration.

SLES11-SP4:/home/username # ip link set mtu 1350 dev eth0
RTNETLINK answers: Invalid argument
SLES11-SP4:/home/username # ifconfig eth0 mtu 1350
SIOCSIFMTU: Invalid argument

We already tried with different values and kernel versions but the issue is persisting.
Any help on this will be appreciate.

**Comment by oniled** [comment]
This doesn't appear to be a lis-rpms related issue.

You should be able to use YAST if using the GUI ( https://www.suse.com/documentation/sles11/book_sle_admin/data/sec_basicnet_yast.html)

or set it in the ifcfg file for the interface.

source: https://support.hpe.com/hpsc/doc/public/display?docId=emr_na-c03612212 and http://www.susegeek.com/networking/how-to-manually-set-the-mtu-maximum-transmission-unit-in-opensuse/

**Comment by shirgall** [comment]
This issue was tracked in https://bugzilla.suse.com/show_bug.cgi?id=1104098 as SUSE delivers built-in Hyper-V device drivers and this particular issue was related to those. The bug is not public, but the fix is available:

SUSE-SU-2019:0148-1: An update that solves 10 vulnerabilities and has 94 fixes is now available.

Category: security (important)
Bug References: 1012382,1015336,1015337,1015340,1019683,1019695,1020645,1027260,1027457,1042286,1043083,1046264,1047487,1048916,1065600,1066223,1068032,1069702,1070805,1079935,1087082,1091405,1093158,1094244,1094973,1096242,1096281,1099523,1100105,1101557,1102439,1102660,1103156,1103257,1103624,1104098,1104731,1105412,1106105,1106237,1106240,1106929,1107385,1108145,1108240,1109272,1109330,1109806,1110286,1111062,1111809,1112246,1112963,1113412,1114190,1114417,1114475,1114648,1114763,1114839,1114871,1115431,1115433,1115440,1115587,1115709,1116027,1116183,1116285,1116336,1116345,1116497,1116841,1116924,1116950,1117162,1117165,1117186,1117562,1118152,1118316,1118319,1118505,1118790,1118798,1118915,1118922,1118926,1118930,1118936,1119204,1119714,1119877,1119946,1119967,1119970,1120046,1120743,1121239,1121240,1121241,1121242,1121275,1121621
CVE References: CVE-2017-16939,CVE-2018-1120,CVE-2018-16862,CVE-2018-16884,CVE-2018-19407,CVE-2018-19824,CVE-2018-19985,CVE-2018-20169,CVE-2018-3639,CVE-2018-9568
Sources used:
SUSE Linux Enterprise Server 12-SP3 (src):    kernel-azure-4.4.170-4.22.1, kernel-source-azure-4.4.170-4.22.1, kernel-syms-azure-4.4.170-4.22.1
